const mysql = require('mysql2');
const dbConfig = require('./config/database');

// Database connection
const db = mysql.createConnection({
    host: dbConfig.host,
    port: dbConfig.port,
    user: dbConfig.user,
    password: dbConfig.password,
    database: dbConfig.database
});

// Comprehensive list of vehicles 2010-2015
const vehicles = [
    // HONDA
    { make: 'Honda', model: 'Accord', year: 2010 },
    { make: 'Honda', model: 'Accord', year: 2011 },
    { make: 'Honda', model: 'Accord', year: 2012 },
    { make: 'Honda', model: 'Accord', year: 2013 },
    { make: 'Honda', model: 'Accord', year: 2014 },
    { make: 'Honda', model: 'Accord', year: 2015 },
    { make: 'Honda', model: 'Civic', year: 2010 },
    { make: 'Honda', model: 'Civic', year: 2011 },
    { make: 'Honda', model: 'Civic', year: 2012 },
    { make: 'Honda', model: 'Civic', year: 2013 },
    { make: 'Honda', model: 'Civic', year: 2014 },
    { make: 'Honda', model: 'Civic', year: 2015 },
    { make: 'Honda', model: 'CR-V', year: 2010 },
    { make: 'Honda', model: 'CR-V', year: 2011 },
    { make: 'Honda', model: 'CR-V', year: 2012 },
    { make: 'Honda', model: 'CR-V', year: 2013 },
    { make: 'Honda', model: 'CR-V', year: 2014 },
    { make: 'Honda', model: 'CR-V', year: 2015 },
    { make: 'Honda', model: 'Crosstour', year: 2010 },
    { make: 'Honda', model: 'Crosstour', year: 2011 },
    { make: 'Honda', model: 'Crosstour', year: 2012 },
    { make: 'Honda', model: 'Crosstour', year: 2013 },
    { make: 'Honda', model: 'Crosstour', year: 2014 },
    { make: 'Honda', model: 'Crosstour', year: 2015 },
    { make: 'Honda', model: 'Fit', year: 2010 },
    { make: 'Honda', model: 'Fit', year: 2011 },
    { make: 'Honda', model: 'Fit', year: 2012 },
    { make: 'Honda', model: 'Fit', year: 2013 },
    { make: 'Honda', model: 'Fit', year: 2014 },
    { make: 'Honda', model: 'Fit', year: 2015 },
    { make: 'Honda', model: 'Pilot', year: 2010 },
    { make: 'Honda', model: 'Pilot', year: 2011 },
    { make: 'Honda', model: 'Pilot', year: 2012 },
    { make: 'Honda', model: 'Pilot', year: 2013 },
    { make: 'Honda', model: 'Pilot', year: 2014 },
    { make: 'Honda', model: 'Pilot', year: 2015 },
    { make: 'Honda', model: 'Odyssey', year: 2010 },
    { make: 'Honda', model: 'Odyssey', year: 2011 },
    { make: 'Honda', model: 'Odyssey', year: 2012 },
    { make: 'Honda', model: 'Odyssey', year: 2013 },
    { make: 'Honda', model: 'Odyssey', year: 2014 },
    { make: 'Honda', model: 'Odyssey', year: 2015 },
    { make: 'Honda', model: 'Ridgeline', year: 2010 },
    { make: 'Honda', model: 'Ridgeline', year: 2011 },
    { make: 'Honda', model: 'Ridgeline', year: 2012 },
    { make: 'Honda', model: 'Ridgeline', year: 2013 },
    { make: 'Honda', model: 'Ridgeline', year: 2014 },
    { make: 'Honda', model: 'Insight', year: 2010 },
    { make: 'Honda', model: 'Insight', year: 2011 },
    { make: 'Honda', model: 'Insight', year: 2012 },
    { make: 'Honda', model: 'Insight', year: 2013 },
    { make: 'Honda', model: 'Insight', year: 2014 },
    { make: 'Honda', model: 'CR-Z', year: 2011 },
    { make: 'Honda', model: 'CR-Z', year: 2012 },
    { make: 'Honda', model: 'CR-Z', year: 2013 },
    { make: 'Honda', model: 'CR-Z', year: 2014 },
    { make: 'Honda', model: 'CR-Z', year: 2015 },

    // TOYOTA
    { make: 'Toyota', model: 'Camry', year: 2010 },
    { make: 'Toyota', model: 'Camry', year: 2011 },
    { make: 'Toyota', model: 'Camry', year: 2012 },
    { make: 'Toyota', model: 'Camry', year: 2013 },
    { make: 'Toyota', model: 'Camry', year: 2014 },
    { make: 'Toyota', model: 'Camry', year: 2015 },
    { make: 'Toyota', model: 'Corolla', year: 2010 },
    { make: 'Toyota', model: 'Corolla', year: 2011 },
    { make: 'Toyota', model: 'Corolla', year: 2012 },
    { make: 'Toyota', model: 'Corolla', year: 2013 },
    { make: 'Toyota', model: 'Corolla', year: 2014 },
    { make: 'Toyota', model: 'Corolla', year: 2015 },
    { make: 'Toyota', model: 'RAV4', year: 2010 },
    { make: 'Toyota', model: 'RAV4', year: 2011 },
    { make: 'Toyota', model: 'RAV4', year: 2012 },
    { make: 'Toyota', model: 'RAV4', year: 2013 },
    { make: 'Toyota', model: 'RAV4', year: 2014 },
    { make: 'Toyota', model: 'RAV4', year: 2015 },
    { make: 'Toyota', model: 'Highlander', year: 2010 },
    { make: 'Toyota', model: 'Highlander', year: 2011 },
    { make: 'Toyota', model: 'Highlander', year: 2012 },
    { make: 'Toyota', model: 'Highlander', year: 2013 },
    { make: 'Toyota', model: 'Highlander', year: 2014 },
    { make: 'Toyota', model: 'Highlander', year: 2015 },
    { make: 'Toyota', model: 'Prius', year: 2010 },
    { make: 'Toyota', model: 'Prius', year: 2011 },
    { make: 'Toyota', model: 'Prius', year: 2012 },
    { make: 'Toyota', model: 'Prius', year: 2013 },
    { make: 'Toyota', model: 'Prius', year: 2014 },
    { make: 'Toyota', model: 'Prius', year: 2015 },
    { make: 'Toyota', model: 'Tacoma', year: 2010 },
    { make: 'Toyota', model: 'Tacoma', year: 2011 },
    { make: 'Toyota', model: 'Tacoma', year: 2012 },
    { make: 'Toyota', model: 'Tacoma', year: 2013 },
    { make: 'Toyota', model: 'Tacoma', year: 2014 },
    { make: 'Toyota', model: 'Tacoma', year: 2015 },
    { make: 'Toyota', model: 'Tundra', year: 2010 },
    { make: 'Toyota', model: 'Tundra', year: 2011 },
    { make: 'Toyota', model: 'Tundra', year: 2012 },
    { make: 'Toyota', model: 'Tundra', year: 2013 },
    { make: 'Toyota', model: 'Tundra', year: 2014 },
    { make: 'Toyota', model: 'Tundra', year: 2015 },
    { make: 'Toyota', model: '4Runner', year: 2010 },
    { make: 'Toyota', model: '4Runner', year: 2011 },
    { make: 'Toyota', model: '4Runner', year: 2012 },
    { make: 'Toyota', model: '4Runner', year: 2013 },
    { make: 'Toyota', model: '4Runner', year: 2014 },
    { make: 'Toyota', model: '4Runner', year: 2015 },
    { make: 'Toyota', model: 'Sienna', year: 2010 },
    { make: 'Toyota', model: 'Sienna', year: 2011 },
    { make: 'Toyota', model: 'Sienna', year: 2012 },
    { make: 'Toyota', model: 'Sienna', year: 2013 },
    { make: 'Toyota', model: 'Sienna', year: 2014 },
    { make: 'Toyota', model: 'Sienna', year: 2015 },
    { make: 'Toyota', model: 'Avalon', year: 2010 },
    { make: 'Toyota', model: 'Avalon', year: 2011 },
    { make: 'Toyota', model: 'Avalon', year: 2012 },
    { make: 'Toyota', model: 'Avalon', year: 2013 },
    { make: 'Toyota', model: 'Avalon', year: 2014 },
    { make: 'Toyota', model: 'Avalon', year: 2015 },
    { make: 'Toyota', model: 'Yaris', year: 2010 },
    { make: 'Toyota', model: 'Yaris', year: 2011 },
    { make: 'Toyota', model: 'Yaris', year: 2012 },
    { make: 'Toyota', model: 'Yaris', year: 2013 },
    { make: 'Toyota', model: 'Yaris', year: 2014 },
    { make: 'Toyota', model: 'Yaris', year: 2015 },
    { make: 'Toyota', model: 'Venza', year: 2010 },
    { make: 'Toyota', model: 'Venza', year: 2011 },
    { make: 'Toyota', model: 'Venza', year: 2012 },
    { make: 'Toyota', model: 'Venza', year: 2013 },
    { make: 'Toyota', model: 'Venza', year: 2014 },
    { make: 'Toyota', model: 'Venza', year: 2015 },

    // FORD
    { make: 'Ford', model: 'F-150', year: 2010 },
    { make: 'Ford', model: 'F-150', year: 2011 },
    { make: 'Ford', model: 'F-150', year: 2012 },
    { make: 'Ford', model: 'F-150', year: 2013 },
    { make: 'Ford', model: 'F-150', year: 2014 },
    { make: 'Ford', model: 'F-150', year: 2015 },
    { make: 'Ford', model: 'Escape', year: 2010 },
    { make: 'Ford', model: 'Escape', year: 2011 },
    { make: 'Ford', model: 'Escape', year: 2012 },
    { make: 'Ford', model: 'Escape', year: 2013 },
    { make: 'Ford', model: 'Escape', year: 2014 },
    { make: 'Ford', model: 'Escape', year: 2015 },
    { make: 'Ford', model: 'Fusion', year: 2010 },
    { make: 'Ford', model: 'Fusion', year: 2011 },
    { make: 'Ford', model: 'Fusion', year: 2012 },
    { make: 'Ford', model: 'Fusion', year: 2013 },
    { make: 'Ford', model: 'Fusion', year: 2014 },
    { make: 'Ford', model: 'Fusion', year: 2015 },
    { make: 'Ford', model: 'Explorer', year: 2010 },
    { make: 'Ford', model: 'Explorer', year: 2011 },
    { make: 'Ford', model: 'Explorer', year: 2012 },
    { make: 'Ford', model: 'Explorer', year: 2013 },
    { make: 'Ford', model: 'Explorer', year: 2014 },
    { make: 'Ford', model: 'Explorer', year: 2015 },
    { make: 'Ford', model: 'Focus', year: 2010 },
    { make: 'Ford', model: 'Focus', year: 2011 },
    { make: 'Ford', model: 'Focus', year: 2012 },
    { make: 'Ford', model: 'Focus', year: 2013 },
    { make: 'Ford', model: 'Focus', year: 2014 },
    { make: 'Ford', model: 'Focus', year: 2015 },
    { make: 'Ford', model: 'Edge', year: 2010 },
    { make: 'Ford', model: 'Edge', year: 2011 },
    { make: 'Ford', model: 'Edge', year: 2012 },
    { make: 'Ford', model: 'Edge', year: 2013 },
    { make: 'Ford', model: 'Edge', year: 2014 },
    { make: 'Ford', model: 'Edge', year: 2015 },
    { make: 'Ford', model: 'Mustang', year: 2010 },
    { make: 'Ford', model: 'Mustang', year: 2011 },
    { make: 'Ford', model: 'Mustang', year: 2012 },
    { make: 'Ford', model: 'Mustang', year: 2013 },
    { make: 'Ford', model: 'Mustang', year: 2014 },
    { make: 'Ford', model: 'Mustang', year: 2015 },
    { make: 'Ford', model: 'Expedition', year: 2010 },
    { make: 'Ford', model: 'Expedition', year: 2011 },
    { make: 'Ford', model: 'Expedition', year: 2012 },
    { make: 'Ford', model: 'Expedition', year: 2013 },
    { make: 'Ford', model: 'Expedition', year: 2014 },
    { make: 'Ford', model: 'Expedition', year: 2015 },
    { make: 'Ford', model: 'Fiesta', year: 2011 },
    { make: 'Ford', model: 'Fiesta', year: 2012 },
    { make: 'Ford', model: 'Fiesta', year: 2013 },
    { make: 'Ford', model: 'Fiesta', year: 2014 },
    { make: 'Ford', model: 'Fiesta', year: 2015 },
    { make: 'Ford', model: 'Taurus', year: 2010 },
    { make: 'Ford', model: 'Taurus', year: 2011 },
    { make: 'Ford', model: 'Taurus', year: 2012 },
    { make: 'Ford', model: 'Taurus', year: 2013 },
    { make: 'Ford', model: 'Taurus', year: 2014 },
    { make: 'Ford', model: 'Taurus', year: 2015 },

    // CHEVROLET
    { make: 'Chevrolet', model: 'Silverado 1500', year: 2010 },
    { make: 'Chevrolet', model: 'Silverado 1500', year: 2011 },
    { make: 'Chevrolet', model: 'Silverado 1500', year: 2012 },
    { make: 'Chevrolet', model: 'Silverado 1500', year: 2013 },
    { make: 'Chevrolet', model: 'Silverado 1500', year: 2014 },
    { make: 'Chevrolet', model: 'Silverado 1500', year: 2015 },
    { make: 'Chevrolet', model: 'Equinox', year: 2010 },
    { make: 'Chevrolet', model: 'Equinox', year: 2011 },
    { make: 'Chevrolet', model: 'Equinox', year: 2012 },
    { make: 'Chevrolet', model: 'Equinox', year: 2013 },
    { make: 'Chevrolet', model: 'Equinox', year: 2014 },
    { make: 'Chevrolet', model: 'Equinox', year: 2015 },
    { make: 'Chevrolet', model: 'Malibu', year: 2010 },
    { make: 'Chevrolet', model: 'Malibu', year: 2011 },
    { make: 'Chevrolet', model: 'Malibu', year: 2012 },
    { make: 'Chevrolet', model: 'Malibu', year: 2013 },
    { make: 'Chevrolet', model: 'Malibu', year: 2014 },
    { make: 'Chevrolet', model: 'Malibu', year: 2015 },
    { make: 'Chevrolet', model: 'Cruze', year: 2011 },
    { make: 'Chevrolet', model: 'Cruze', year: 2012 },
    { make: 'Chevrolet', model: 'Cruze', year: 2013 },
    { make: 'Chevrolet', model: 'Cruze', year: 2014 },
    { make: 'Chevrolet', model: 'Cruze', year: 2015 },
    { make: 'Chevrolet', model: 'Traverse', year: 2010 },
    { make: 'Chevrolet', model: 'Traverse', year: 2011 },
    { make: 'Chevrolet', model: 'Traverse', year: 2012 },
    { make: 'Chevrolet', model: 'Traverse', year: 2013 },
    { make: 'Chevrolet', model: 'Traverse', year: 2014 },
    { make: 'Chevrolet', model: 'Traverse', year: 2015 },
    { make: 'Chevrolet', model: 'Tahoe', year: 2010 },
    { make: 'Chevrolet', model: 'Tahoe', year: 2011 },
    { make: 'Chevrolet', model: 'Tahoe', year: 2012 },
    { make: 'Chevrolet', model: 'Tahoe', year: 2013 },
    { make: 'Chevrolet', model: 'Tahoe', year: 2014 },
    { make: 'Chevrolet', model: 'Tahoe', year: 2015 },
    { make: 'Chevrolet', model: 'Camaro', year: 2010 },
    { make: 'Chevrolet', model: 'Camaro', year: 2011 },
    { make: 'Chevrolet', model: 'Camaro', year: 2012 },
    { make: 'Chevrolet', model: 'Camaro', year: 2013 },
    { make: 'Chevrolet', model: 'Camaro', year: 2014 },
    { make: 'Chevrolet', model: 'Camaro', year: 2015 },
    { make: 'Chevrolet', model: 'Impala', year: 2010 },
    { make: 'Chevrolet', model: 'Impala', year: 2011 },
    { make: 'Chevrolet', model: 'Impala', year: 2012 },
    { make: 'Chevrolet', model: 'Impala', year: 2013 },
    { make: 'Chevrolet', model: 'Impala', year: 2014 },
    { make: 'Chevrolet', model: 'Impala', year: 2015 },
    { make: 'Chevrolet', model: 'Suburban', year: 2010 },
    { make: 'Chevrolet', model: 'Suburban', year: 2011 },
    { make: 'Chevrolet', model: 'Suburban', year: 2012 },
    { make: 'Chevrolet', model: 'Suburban', year: 2013 },
    { make: 'Chevrolet', model: 'Suburban', year: 2014 },
    { make: 'Chevrolet', model: 'Suburban', year: 2015 },
    { make: 'Chevrolet', model: 'Sonic', year: 2012 },
    { make: 'Chevrolet', model: 'Sonic', year: 2013 },
    { make: 'Chevrolet', model: 'Sonic', year: 2014 },
    { make: 'Chevrolet', model: 'Sonic', year: 2015 },
    { make: 'Chevrolet', model: 'Colorado', year: 2015 },

    // NISSAN
    { make: 'Nissan', model: 'Altima', year: 2010 },
    { make: 'Nissan', model: 'Altima', year: 2011 },
    { make: 'Nissan', model: 'Altima', year: 2012 },
    { make: 'Nissan', model: 'Altima', year: 2013 },
    { make: 'Nissan', model: 'Altima', year: 2014 },
    { make: 'Nissan', model: 'Altima', year: 2015 },
    { make: 'Nissan', model: 'Sentra', year: 2010 },
    { make: 'Nissan', model: 'Sentra', year: 2011 },
    { make: 'Nissan', model: 'Sentra', year: 2012 },
    { make: 'Nissan', model: 'Sentra', year: 2013 },
    { make: 'Nissan', model: 'Sentra', year: 2014 },
    { make: 'Nissan', model: 'Sentra', year: 2015 },
    { make: 'Nissan', model: 'Rogue', year: 2010 },
    { make: 'Nissan', model: 'Rogue', year: 2011 },
    { make: 'Nissan', model: 'Rogue', year: 2012 },
    { make: 'Nissan', model: 'Rogue', year: 2013 },
    { make: 'Nissan', model: 'Rogue', year: 2014 },
    { make: 'Nissan', model: 'Rogue', year: 2015 },
    { make: 'Nissan', model: 'Maxima', year: 2010 },
    { make: 'Nissan', model: 'Maxima', year: 2011 },
    { make: 'Nissan', model: 'Maxima', year: 2012 },
    { make: 'Nissan', model: 'Maxima', year: 2013 },
    { make: 'Nissan', model: 'Maxima', year: 2014 },
    { make: 'Nissan', model: 'Maxima', year: 2015 },
    { make: 'Nissan', model: 'Pathfinder', year: 2010 },
    { make: 'Nissan', model: 'Pathfinder', year: 2011 },
    { make: 'Nissan', model: 'Pathfinder', year: 2012 },
    { make: 'Nissan', model: 'Pathfinder', year: 2013 },
    { make: 'Nissan', model: 'Pathfinder', year: 2014 },
    { make: 'Nissan', model: 'Pathfinder', year: 2015 },
    { make: 'Nissan', model: 'Frontier', year: 2010 },
    { make: 'Nissan', model: 'Frontier', year: 2011 },
    { make: 'Nissan', model: 'Frontier', year: 2012 },
    { make: 'Nissan', model: 'Frontier', year: 2013 },
    { make: 'Nissan', model: 'Frontier', year: 2014 },
    { make: 'Nissan', model: 'Frontier', year: 2015 },
    { make: 'Nissan', model: 'Versa', year: 2010 },
    { make: 'Nissan', model: 'Versa', year: 2011 },
    { make: 'Nissan', model: 'Versa', year: 2012 },
    { make: 'Nissan', model: 'Versa', year: 2013 },
    { make: 'Nissan', model: 'Versa', year: 2014 },
    { make: 'Nissan', model: 'Versa', year: 2015 },
    { make: 'Nissan', model: 'Murano', year: 2010 },
    { make: 'Nissan', model: 'Murano', year: 2011 },
    { make: 'Nissan', model: 'Murano', year: 2012 },
    { make: 'Nissan', model: 'Murano', year: 2013 },
    { make: 'Nissan', model: 'Murano', year: 2014 },
    { make: 'Nissan', model: 'Murano', year: 2015 },
    { make: 'Nissan', model: '370Z', year: 2010 },
    { make: 'Nissan', model: '370Z', year: 2011 },
    { make: 'Nissan', model: '370Z', year: 2012 },
    { make: 'Nissan', model: '370Z', year: 2013 },
    { make: 'Nissan', model: '370Z', year: 2014 },
    { make: 'Nissan', model: '370Z', year: 2015 },
    { make: 'Nissan', model: 'Titan', year: 2010 },
    { make: 'Nissan', model: 'Titan', year: 2011 },
    { make: 'Nissan', model: 'Titan', year: 2012 },
    { make: 'Nissan', model: 'Titan', year: 2013 },
    { make: 'Nissan', model: 'Titan', year: 2014 },
    { make: 'Nissan', model: 'Titan', year: 2015 },

    // JEEP
    { make: 'Jeep', model: 'Wrangler', year: 2010 },
    { make: 'Jeep', model: 'Wrangler', year: 2011 },
    { make: 'Jeep', model: 'Wrangler', year: 2012 },
    { make: 'Jeep', model: 'Wrangler', year: 2013 },
    { make: 'Jeep', model: 'Wrangler', year: 2014 },
    { make: 'Jeep', model: 'Wrangler', year: 2015 },
    { make: 'Jeep', model: 'Grand Cherokee', year: 2010 },
    { make: 'Jeep', model: 'Grand Cherokee', year: 2011 },
    { make: 'Jeep', model: 'Grand Cherokee', year: 2012 },
    { make: 'Jeep', model: 'Grand Cherokee', year: 2013 },
    { make: 'Jeep', model: 'Grand Cherokee', year: 2014 },
    { make: 'Jeep', model: 'Grand Cherokee', year: 2015 },
    { make: 'Jeep', model: 'Cherokee', year: 2014 },
    { make: 'Jeep', model: 'Cherokee', year: 2015 },
    { make: 'Jeep', model: 'Compass', year: 2010 },
    { make: 'Jeep', model: 'Compass', year: 2011 },
    { make: 'Jeep', model: 'Compass', year: 2012 },
    { make: 'Jeep', model: 'Compass', year: 2013 },
    { make: 'Jeep', model: 'Compass', year: 2014 },
    { make: 'Jeep', model: 'Compass', year: 2015 },
    { make: 'Jeep', model: 'Patriot', year: 2010 },
    { make: 'Jeep', model: 'Patriot', year: 2011 },
    { make: 'Jeep', model: 'Patriot', year: 2012 },
    { make: 'Jeep', model: 'Patriot', year: 2013 },
    { make: 'Jeep', model: 'Patriot', year: 2014 },
    { make: 'Jeep', model: 'Patriot', year: 2015 },
    { make: 'Jeep', model: 'Renegade', year: 2015 },

    // RAM
    { make: 'Ram', model: '1500', year: 2011 },
    { make: 'Ram', model: '1500', year: 2012 },
    { make: 'Ram', model: '1500', year: 2013 },
    { make: 'Ram', model: '1500', year: 2014 },
    { make: 'Ram', model: '1500', year: 2015 },
    { make: 'Ram', model: '2500', year: 2011 },
    { make: 'Ram', model: '2500', year: 2012 },
    { make: 'Ram', model: '2500', year: 2013 },
    { make: 'Ram', model: '2500', year: 2014 },
    { make: 'Ram', model: '2500', year: 2015 },

    // DODGE
    { make: 'Dodge', model: 'Charger', year: 2010 },
    { make: 'Dodge', model: 'Charger', year: 2011 },
    { make: 'Dodge', model: 'Charger', year: 2012 },
    { make: 'Dodge', model: 'Charger', year: 2013 },
    { make: 'Dodge', model: 'Charger', year: 2014 },
    { make: 'Dodge', model: 'Charger', year: 2015 },
    { make: 'Dodge', model: 'Challenger', year: 2010 },
    { make: 'Dodge', model: 'Challenger', year: 2011 },
    { make: 'Dodge', model: 'Challenger', year: 2012 },
    { make: 'Dodge', model: 'Challenger', year: 2013 },
    { make: 'Dodge', model: 'Challenger', year: 2014 },
    { make: 'Dodge', model: 'Challenger', year: 2015 },
    { make: 'Dodge', model: 'Durango', year: 2011 },
    { make: 'Dodge', model: 'Durango', year: 2012 },
    { make: 'Dodge', model: 'Durango', year: 2013 },
    { make: 'Dodge', model: 'Durango', year: 2014 },
    { make: 'Dodge', model: 'Durango', year: 2015 },
    { make: 'Dodge', model: 'Journey', year: 2010 },
    { make: 'Dodge', model: 'Journey', year: 2011 },
    { make: 'Dodge', model: 'Journey', year: 2012 },
    { make: 'Dodge', model: 'Journey', year: 2013 },
    { make: 'Dodge', model: 'Journey', year: 2014 },
    { make: 'Dodge', model: 'Journey', year: 2015 },
    { make: 'Dodge', model: 'Dart', year: 2013 },
    { make: 'Dodge', model: 'Dart', year: 2014 },
    { make: 'Dodge', model: 'Dart', year: 2015 },

    // GMC
    { make: 'GMC', model: 'Sierra 1500', year: 2010 },
    { make: 'GMC', model: 'Sierra 1500', year: 2011 },
    { make: 'GMC', model: 'Sierra 1500', year: 2012 },
    { make: 'GMC', model: 'Sierra 1500', year: 2013 },
    { make: 'GMC', model: 'Sierra 1500', year: 2014 },
    { make: 'GMC', model: 'Sierra 1500', year: 2015 },
    { make: 'GMC', model: 'Terrain', year: 2010 },
    { make: 'GMC', model: 'Terrain', year: 2011 },
    { make: 'GMC', model: 'Terrain', year: 2012 },
    { make: 'GMC', model: 'Terrain', year: 2013 },
    { make: 'GMC', model: 'Terrain', year: 2014 },
    { make: 'GMC', model: 'Terrain', year: 2015 },
    { make: 'GMC', model: 'Acadia', year: 2010 },
    { make: 'GMC', model: 'Acadia', year: 2011 },
    { make: 'GMC', model: 'Acadia', year: 2012 },
    { make: 'GMC', model: 'Acadia', year: 2013 },
    { make: 'GMC', model: 'Acadia', year: 2014 },
    { make: 'GMC', model: 'Acadia', year: 2015 },
    { make: 'GMC', model: 'Yukon', year: 2010 },
    { make: 'GMC', model: 'Yukon', year: 2011 },
    { make: 'GMC', model: 'Yukon', year: 2012 },
    { make: 'GMC', model: 'Yukon', year: 2013 },
    { make: 'GMC', model: 'Yukon', year: 2014 },
    { make: 'GMC', model: 'Yukon', year: 2015 },
    { make: 'GMC', model: 'Canyon', year: 2015 },

    // HYUNDAI
    { make: 'Hyundai', model: 'Elantra', year: 2010 },
    { make: 'Hyundai', model: 'Elantra', year: 2011 },
    { make: 'Hyundai', model: 'Elantra', year: 2012 },
    { make: 'Hyundai', model: 'Elantra', year: 2013 },
    { make: 'Hyundai', model: 'Elantra', year: 2014 },
    { make: 'Hyundai', model: 'Elantra', year: 2015 },
    { make: 'Hyundai', model: 'Sonata', year: 2010 },
    { make: 'Hyundai', model: 'Sonata', year: 2011 },
    { make: 'Hyundai', model: 'Sonata', year: 2012 },
    { make: 'Hyundai', model: 'Sonata', year: 2013 },
    { make: 'Hyundai', model: 'Sonata', year: 2014 },
    { make: 'Hyundai', model: 'Sonata', year: 2015 },
    { make: 'Hyundai', model: 'Tucson', year: 2010 },
    { make: 'Hyundai', model: 'Tucson', year: 2011 },
    { make: 'Hyundai', model: 'Tucson', year: 2012 },
    { make: 'Hyundai', model: 'Tucson', year: 2013 },
    { make: 'Hyundai', model: 'Tucson', year: 2014 },
    { make: 'Hyundai', model: 'Tucson', year: 2015 },
    { make: 'Hyundai', model: 'Santa Fe', year: 2010 },
    { make: 'Hyundai', model: 'Santa Fe', year: 2011 },
    { make: 'Hyundai', model: 'Santa Fe', year: 2012 },
    { make: 'Hyundai', model: 'Santa Fe', year: 2013 },
    { make: 'Hyundai', model: 'Santa Fe', year: 2014 },
    { make: 'Hyundai', model: 'Santa Fe', year: 2015 },
    { make: 'Hyundai', model: 'Accent', year: 2010 },
    { make: 'Hyundai', model: 'Accent', year: 2011 },
    { make: 'Hyundai', model: 'Accent', year: 2012 },
    { make: 'Hyundai', model: 'Accent', year: 2013 },
    { make: 'Hyundai', model: 'Accent', year: 2014 },
    { make: 'Hyundai', model: 'Accent', year: 2015 },
    { make: 'Hyundai', model: 'Genesis', year: 2010 },
    { make: 'Hyundai', model: 'Genesis', year: 2011 },
    { make: 'Hyundai', model: 'Genesis', year: 2012 },
    { make: 'Hyundai', model: 'Genesis', year: 2013 },
    { make: 'Hyundai', model: 'Genesis', year: 2014 },
    { make: 'Hyundai', model: 'Genesis', year: 2015 },

    // KIA
    { make: 'Kia', model: 'Optima', year: 2010 },
    { make: 'Kia', model: 'Optima', year: 2011 },
    { make: 'Kia', model: 'Optima', year: 2012 },
    { make: 'Kia', model: 'Optima', year: 2013 },
    { make: 'Kia', model: 'Optima', year: 2014 },
    { make: 'Kia', model: 'Optima', year: 2015 },
    { make: 'Kia', model: 'Sorento', year: 2011 },
    { make: 'Kia', model: 'Sorento', year: 2012 },
    { make: 'Kia', model: 'Sorento', year: 2013 },
    { make: 'Kia', model: 'Sorento', year: 2014 },
    { make: 'Kia', model: 'Sorento', year: 2015 },
    { make: 'Kia', model: 'Soul', year: 2010 },
    { make: 'Kia', model: 'Soul', year: 2011 },
    { make: 'Kia', model: 'Soul', year: 2012 },
    { make: 'Kia', model: 'Soul', year: 2013 },
    { make: 'Kia', model: 'Soul', year: 2014 },
    { make: 'Kia', model: 'Soul', year: 2015 },
    { make: 'Kia', model: 'Sportage', year: 2011 },
    { make: 'Kia', model: 'Sportage', year: 2012 },
    { make: 'Kia', model: 'Sportage', year: 2013 },
    { make: 'Kia', model: 'Sportage', year: 2014 },
    { make: 'Kia', model: 'Sportage', year: 2015 },
    { make: 'Kia', model: 'Forte', year: 2010 },
    { make: 'Kia', model: 'Forte', year: 2011 },
    { make: 'Kia', model: 'Forte', year: 2012 },
    { make: 'Kia', model: 'Forte', year: 2013 },
    { make: 'Kia', model: 'Forte', year: 2014 },
    { make: 'Kia', model: 'Forte', year: 2015 },
    { make: 'Kia', model: 'Rio', year: 2012 },
    { make: 'Kia', model: 'Rio', year: 2013 },
    { make: 'Kia', model: 'Rio', year: 2014 },
    { make: 'Kia', model: 'Rio', year: 2015 },

    // SUBARU
    { make: 'Subaru', model: 'Outback', year: 2010 },
    { make: 'Subaru', model: 'Outback', year: 2011 },
    { make: 'Subaru', model: 'Outback', year: 2012 },
    { make: 'Subaru', model: 'Outback', year: 2013 },
    { make: 'Subaru', model: 'Outback', year: 2014 },
    { make: 'Subaru', model: 'Outback', year: 2015 },
    { make: 'Subaru', model: 'Forester', year: 2010 },
    { make: 'Subaru', model: 'Forester', year: 2011 },
    { make: 'Subaru', model: 'Forester', year: 2012 },
    { make: 'Subaru', model: 'Forester', year: 2013 },
    { make: 'Subaru', model: 'Forester', year: 2014 },
    { make: 'Subaru', model: 'Forester', year: 2015 },
    { make: 'Subaru', model: 'Impreza', year: 2010 },
    { make: 'Subaru', model: 'Impreza', year: 2011 },
    { make: 'Subaru', model: 'Impreza', year: 2012 },
    { make: 'Subaru', model: 'Impreza', year: 2013 },
    { make: 'Subaru', model: 'Impreza', year: 2014 },
    { make: 'Subaru', model: 'Impreza', year: 2015 },
    { make: 'Subaru', model: 'Legacy', year: 2010 },
    { make: 'Subaru', model: 'Legacy', year: 2011 },
    { make: 'Subaru', model: 'Legacy', year: 2012 },
    { make: 'Subaru', model: 'Legacy', year: 2013 },
    { make: 'Subaru', model: 'Legacy', year: 2014 },
    { make: 'Subaru', model: 'Legacy', year: 2015 },
    { make: 'Subaru', model: 'WRX', year: 2015 },
    { make: 'Subaru', model: 'XV Crosstrek', year: 2013 },
    { make: 'Subaru', model: 'XV Crosstrek', year: 2014 },
    { make: 'Subaru', model: 'XV Crosstrek', year: 2015 },

    // MAZDA
    { make: 'Mazda', model: 'Mazda3', year: 2010 },
    { make: 'Mazda', model: 'Mazda3', year: 2011 },
    { make: 'Mazda', model: 'Mazda3', year: 2012 },
    { make: 'Mazda', model: 'Mazda3', year: 2013 },
    { make: 'Mazda', model: 'Mazda3', year: 2014 },
    { make: 'Mazda', model: 'Mazda3', year: 2015 },
    { make: 'Mazda', model: 'CX-5', year: 2013 },
    { make: 'Mazda', model: 'CX-5', year: 2014 },
    { make: 'Mazda', model: 'CX-5', year: 2015 },
    { make: 'Mazda', model: 'Mazda6', year: 2010 },
    { make: 'Mazda', model: 'Mazda6', year: 2011 },
    { make: 'Mazda', model: 'Mazda6', year: 2012 },
    { make: 'Mazda', model: 'Mazda6', year: 2013 },
    { make: 'Mazda', model: 'Mazda6', year: 2014 },
    { make: 'Mazda', model: 'Mazda6', year: 2015 },
    { make: 'Mazda', model: 'CX-9', year: 2010 },
    { make: 'Mazda', model: 'CX-9', year: 2011 },
    { make: 'Mazda', model: 'CX-9', year: 2012 },
    { make: 'Mazda', model: 'CX-9', year: 2013 },
    { make: 'Mazda', model: 'CX-9', year: 2014 },
    { make: 'Mazda', model: 'CX-9', year: 2015 },
    { make: 'Mazda', model: 'MX-5 Miata', year: 2010 },
    { make: 'Mazda', model: 'MX-5 Miata', year: 2011 },
    { make: 'Mazda', model: 'MX-5 Miata', year: 2012 },
    { make: 'Mazda', model: 'MX-5 Miata', year: 2013 },
    { make: 'Mazda', model: 'MX-5 Miata', year: 2014 },
    { make: 'Mazda', model: 'MX-5 Miata', year: 2015 },

    // VOLKSWAGEN
    { make: 'Volkswagen', model: 'Jetta', year: 2010 },
    { make: 'Volkswagen', model: 'Jetta', year: 2011 },
    { make: 'Volkswagen', model: 'Jetta', year: 2012 },
    { make: 'Volkswagen', model: 'Jetta', year: 2013 },
    { make: 'Volkswagen', model: 'Jetta', year: 2014 },
    { make: 'Volkswagen', model: 'Jetta', year: 2015 },
    { make: 'Volkswagen', model: 'Passat', year: 2010 },
    { make: 'Volkswagen', model: 'Passat', year: 2011 },
    { make: 'Volkswagen', model: 'Passat', year: 2012 },
    { make: 'Volkswagen', model: 'Passat', year: 2013 },
    { make: 'Volkswagen', model: 'Passat', year: 2014 },
    { make: 'Volkswagen', model: 'Passat', year: 2015 },
    { make: 'Volkswagen', model: 'Tiguan', year: 2010 },
    { make: 'Volkswagen', model: 'Tiguan', year: 2011 },
    { make: 'Volkswagen', model: 'Tiguan', year: 2012 },
    { make: 'Volkswagen', model: 'Tiguan', year: 2013 },
    { make: 'Volkswagen', model: 'Tiguan', year: 2014 },
    { make: 'Volkswagen', model: 'Tiguan', year: 2015 },
    { make: 'Volkswagen', model: 'Golf', year: 2010 },
    { make: 'Volkswagen', model: 'Golf', year: 2011 },
    { make: 'Volkswagen', model: 'Golf', year: 2012 },
    { make: 'Volkswagen', model: 'Golf', year: 2013 },
    { make: 'Volkswagen', model: 'Golf', year: 2014 },
    { make: 'Volkswagen', model: 'Golf', year: 2015 },
    { make: 'Volkswagen', model: 'Beetle', year: 2012 },
    { make: 'Volkswagen', model: 'Beetle', year: 2013 },
    { make: 'Volkswagen', model: 'Beetle', year: 2014 },
    { make: 'Volkswagen', model: 'Beetle', year: 2015 },

    // ACURA
    { make: 'Acura', model: 'TL', year: 2010 },
    { make: 'Acura', model: 'TL', year: 2011 },
    { make: 'Acura', model: 'TL', year: 2012 },
    { make: 'Acura', model: 'TL', year: 2013 },
    { make: 'Acura', model: 'TL', year: 2014 },
    { make: 'Acura', model: 'TLX', year: 2015 },
    { make: 'Acura', model: 'MDX', year: 2010 },
    { make: 'Acura', model: 'MDX', year: 2011 },
    { make: 'Acura', model: 'MDX', year: 2012 },
    { make: 'Acura', model: 'MDX', year: 2013 },
    { make: 'Acura', model: 'MDX', year: 2014 },
    { make: 'Acura', model: 'MDX', year: 2015 },
    { make: 'Acura', model: 'RDX', year: 2010 },
    { make: 'Acura', model: 'RDX', year: 2011 },
    { make: 'Acura', model: 'RDX', year: 2012 },
    { make: 'Acura', model: 'RDX', year: 2013 },
    { make: 'Acura', model: 'RDX', year: 2014 },
    { make: 'Acura', model: 'RDX', year: 2015 },
    { make: 'Acura', model: 'TSX', year: 2010 },
    { make: 'Acura', model: 'TSX', year: 2011 },
    { make: 'Acura', model: 'TSX', year: 2012 },
    { make: 'Acura', model: 'TSX', year: 2013 },
    { make: 'Acura', model: 'TSX', year: 2014 },
    { make: 'Acura', model: 'ILX', year: 2013 },
    { make: 'Acura', model: 'ILX', year: 2014 },
    { make: 'Acura', model: 'ILX', year: 2015 },

    // LEXUS
    { make: 'Lexus', model: 'RX 350', year: 2010 },
    { make: 'Lexus', model: 'RX 350', year: 2011 },
    { make: 'Lexus', model: 'RX 350', year: 2012 },
    { make: 'Lexus', model: 'RX 350', year: 2013 },
    { make: 'Lexus', model: 'RX 350', year: 2014 },
    { make: 'Lexus', model: 'RX 350', year: 2015 },
    { make: 'Lexus', model: 'ES 350', year: 2010 },
    { make: 'Lexus', model: 'ES 350', year: 2011 },
    { make: 'Lexus', model: 'ES 350', year: 2012 },
    { make: 'Lexus', model: 'ES 350', year: 2013 },
    { make: 'Lexus', model: 'ES 350', year: 2014 },
    { make: 'Lexus', model: 'ES 350', year: 2015 },
    { make: 'Lexus', model: 'IS 250', year: 2010 },
    { make: 'Lexus', model: 'IS 250', year: 2011 },
    { make: 'Lexus', model: 'IS 250', year: 2012 },
    { make: 'Lexus', model: 'IS 250', year: 2013 },
    { make: 'Lexus', model: 'IS 250', year: 2014 },
    { make: 'Lexus', model: 'IS 250', year: 2015 },
    { make: 'Lexus', model: 'GX 460', year: 2010 },
    { make: 'Lexus', model: 'GX 460', year: 2011 },
    { make: 'Lexus', model: 'GX 460', year: 2012 },
    { make: 'Lexus', model: 'GX 460', year: 2013 },
    { make: 'Lexus', model: 'GX 460', year: 2014 },
    { make: 'Lexus', model: 'GX 460', year: 2015 },
    { make: 'Lexus', model: 'NX 200t', year: 2015 },

    // BMW
    { make: 'BMW', model: '3 Series', year: 2010 },
    { make: 'BMW', model: '3 Series', year: 2011 },
    { make: 'BMW', model: '3 Series', year: 2012 },
    { make: 'BMW', model: '3 Series', year: 2013 },
    { make: 'BMW', model: '3 Series', year: 2014 },
    { make: 'BMW', model: '3 Series', year: 2015 },
    { make: 'BMW', model: '5 Series', year: 2010 },
    { make: 'BMW', model: '5 Series', year: 2011 },
    { make: 'BMW', model: '5 Series', year: 2012 },
    { make: 'BMW', model: '5 Series', year: 2013 },
    { make: 'BMW', model: '5 Series', year: 2014 },
    { make: 'BMW', model: '5 Series', year: 2015 },
    { make: 'BMW', model: 'X3', year: 2011 },
    { make: 'BMW', model: 'X3', year: 2012 },
    { make: 'BMW', model: 'X3', year: 2013 },
    { make: 'BMW', model: 'X3', year: 2014 },
    { make: 'BMW', model: 'X3', year: 2015 },
    { make: 'BMW', model: 'X5', year: 2010 },
    { make: 'BMW', model: 'X5', year: 2011 },
    { make: 'BMW', model: 'X5', year: 2012 },
    { make: 'BMW', model: 'X5', year: 2013 },
    { make: 'BMW', model: 'X5', year: 2014 },
    { make: 'BMW', model: 'X5', year: 2015 },

    // MERCEDES-BENZ
    { make: 'Mercedes-Benz', model: 'C-Class', year: 2010 },
    { make: 'Mercedes-Benz', model: 'C-Class', year: 2011 },
    { make: 'Mercedes-Benz', model: 'C-Class', year: 2012 },
    { make: 'Mercedes-Benz', model: 'C-Class', year: 2013 },
    { make: 'Mercedes-Benz', model: 'C-Class', year: 2014 },
    { make: 'Mercedes-Benz', model: 'C-Class', year: 2015 },
    { make: 'Mercedes-Benz', model: 'E-Class', year: 2010 },
    { make: 'Mercedes-Benz', model: 'E-Class', year: 2011 },
    { make: 'Mercedes-Benz', model: 'E-Class', year: 2012 },
    { make: 'Mercedes-Benz', model: 'E-Class', year: 2013 },
    { make: 'Mercedes-Benz', model: 'E-Class', year: 2014 },
    { make: 'Mercedes-Benz', model: 'E-Class', year: 2015 },
    { make: 'Mercedes-Benz', model: 'M-Class', year: 2010 },
    { make: 'Mercedes-Benz', model: 'M-Class', year: 2011 },
    { make: 'Mercedes-Benz', model: 'M-Class', year: 2012 },
    { make: 'Mercedes-Benz', model: 'M-Class', year: 2013 },
    { make: 'Mercedes-Benz', model: 'M-Class', year: 2014 },
    { make: 'Mercedes-Benz', model: 'M-Class', year: 2015 },
    { make: 'Mercedes-Benz', model: 'GL-Class', year: 2010 },
    { make: 'Mercedes-Benz', model: 'GL-Class', year: 2011 },
    { make: 'Mercedes-Benz', model: 'GL-Class', year: 2012 },
    { make: 'Mercedes-Benz', model: 'GL-Class', year: 2013 },
    { make: 'Mercedes-Benz', model: 'GL-Class', year: 2014 },
    { make: 'Mercedes-Benz', model: 'GL-Class', year: 2015 },

    // AUDI
    { make: 'Audi', model: 'A4', year: 2010 },
    { make: 'Audi', model: 'A4', year: 2011 },
    { make: 'Audi', model: 'A4', year: 2012 },
    { make: 'Audi', model: 'A4', year: 2013 },
    { make: 'Audi', model: 'A4', year: 2014 },
    { make: 'Audi', model: 'A4', year: 2015 },
    { make: 'Audi', model: 'Q5', year: 2010 },
    { make: 'Audi', model: 'Q5', year: 2011 },
    { make: 'Audi', model: 'Q5', year: 2012 },
    { make: 'Audi', model: 'Q5', year: 2013 },
    { make: 'Audi', model: 'Q5', year: 2014 },
    { make: 'Audi', model: 'Q5', year: 2015 },
    { make: 'Audi', model: 'A6', year: 2010 },
    { make: 'Audi', model: 'A6', year: 2011 },
    { make: 'Audi', model: 'A6', year: 2012 },
    { make: 'Audi', model: 'A6', year: 2013 },
    { make: 'Audi', model: 'A6', year: 2014 },
    { make: 'Audi', model: 'A6', year: 2015 },
    { make: 'Audi', model: 'A3', year: 2015 },
    { make: 'Audi', model: 'Q3', year: 2015 },

    // CADILLAC
    { make: 'Cadillac', model: 'SRX', year: 2010 },
    { make: 'Cadillac', model: 'SRX', year: 2011 },
    { make: 'Cadillac', model: 'SRX', year: 2012 },
    { make: 'Cadillac', model: 'SRX', year: 2013 },
    { make: 'Cadillac', model: 'SRX', year: 2014 },
    { make: 'Cadillac', model: 'SRX', year: 2015 },
    { make: 'Cadillac', model: 'Escalade', year: 2010 },
    { make: 'Cadillac', model: 'Escalade', year: 2011 },
    { make: 'Cadillac', model: 'Escalade', year: 2012 },
    { make: 'Cadillac', model: 'Escalade', year: 2013 },
    { make: 'Cadillac', model: 'Escalade', year: 2014 },
    { make: 'Cadillac', model: 'Escalade', year: 2015 },
    { make: 'Cadillac', model: 'CTS', year: 2010 },
    { make: 'Cadillac', model: 'CTS', year: 2011 },
    { make: 'Cadillac', model: 'CTS', year: 2012 },
    { make: 'Cadillac', model: 'CTS', year: 2013 },
    { make: 'Cadillac', model: 'CTS', year: 2014 },
    { make: 'Cadillac', model: 'CTS', year: 2015 },
    { make: 'Cadillac', model: 'ATS', year: 2013 },
    { make: 'Cadillac', model: 'ATS', year: 2014 },
    { make: 'Cadillac', model: 'ATS', year: 2015 },

    // BUICK
    { make: 'Buick', model: 'Enclave', year: 2010 },
    { make: 'Buick', model: 'Enclave', year: 2011 },
    { make: 'Buick', model: 'Enclave', year: 2012 },
    { make: 'Buick', model: 'Enclave', year: 2013 },
    { make: 'Buick', model: 'Enclave', year: 2014 },
    { make: 'Buick', model: 'Enclave', year: 2015 },
    { make: 'Buick', model: 'LaCrosse', year: 2010 },
    { make: 'Buick', model: 'LaCrosse', year: 2011 },
    { make: 'Buick', model: 'LaCrosse', year: 2012 },
    { make: 'Buick', model: 'LaCrosse', year: 2013 },
    { make: 'Buick', model: 'LaCrosse', year: 2014 },
    { make: 'Buick', model: 'LaCrosse', year: 2015 },
    { make: 'Buick', model: 'Verano', year: 2012 },
    { make: 'Buick', model: 'Verano', year: 2013 },
    { make: 'Buick', model: 'Verano', year: 2014 },
    { make: 'Buick', model: 'Verano', year: 2015 },
    { make: 'Buick', model: 'Encore', year: 2013 },
    { make: 'Buick', model: 'Encore', year: 2014 },
    { make: 'Buick', model: 'Encore', year: 2015 }
];

console.log(`Seeding ${vehicles.length} vehicles from 2010-2015...`);

// Connect to database
db.connect((err) => {
    if (err) {
        console.error('Database connection failed:', err.message);
        return;
    }
    console.log('Connected to MySQL database');

    // Check if vehicle_reference table exists
    db.query('SHOW TABLES LIKE "vehicle_reference"', (err, results) => {
        if (err) {
            console.error('Error checking tables:', err);
            db.end();
            return;
        }

        if (results.length === 0) {
            console.error('vehicle_reference table does not exist!');
            console.log('Please run: node migrate.js first');
            db.end();
            return;
        }

        // Insert vehicles in batches
        const batchSize = 100;
        let inserted = 0;
        let errors = 0;

        const insertBatch = (startIndex) => {
            if (startIndex >= vehicles.length) {
                console.log(`\n✅ Completed! Inserted ${inserted} vehicles, ${errors} errors`);
                db.end();
                return;
            }

            const batch = vehicles.slice(startIndex, startIndex + batchSize);
            const values = batch.map(v => [v.make, v.model, v.year]);

            const query = 'INSERT INTO vehicle_reference (make, model, year) VALUES ?';

            db.query(query, [values], (err, result) => {
                if (err) {
                    console.error(`Error inserting batch starting at ${startIndex}:`, err.message);
                    errors += batch.length;
                } else {
                    inserted += result.affectedRows;
                    process.stdout.write(`\rProgress: ${inserted}/${vehicles.length} vehicles inserted...`);
                }

                // Insert next batch
                insertBatch(startIndex + batchSize);
            });
        };

        // Clear existing data first
        console.log('Clearing existing vehicle reference data...');
        db.query('DELETE FROM vehicle_reference', (err) => {
            if (err) {
                console.error('Error clearing table:', err);
                db.end();
                return;
            }

            console.log('Starting to insert vehicles...');
            insertBatch(0);
        });
    });
});
